
# Quickstart {#quickstart}

The `plumber` package allows you to create APIs by merely decorating your existing R code with special annotations. The example below shows a file named `plumber.R` (the conventional name for Plumber APIs) which defines an API.

```{r, echo=FALSE, results='asis'}
include_r("files/apis/01-01-quickstart.R")
```

This file defines two Plumber "endpoints." One is hosted at the path `/rand` and generates some random numbers then returns a summary; the other is hosted at the path `/graph` and returns an image showing a simple R plot.

If you haven't installed `plumber` yet, see the [installation section](#installation). Once  you have plumber installed, you can use the `plumber::plumb` function to translate this R file into a Plumber API:

```r
pr <- plumber::plumb("plumber.R")
```

The `pr` object now encapsulates all the logic represented in your `plumber.R` file. The next step is to bring the API to life using the `run` method:

```r
pr$run()
```

You should see a message about your API running on your computer on port `8000`.  If you're running this code locally on your personal machine, you should be able to open http://localhost:8000/rand or http://localhost:8000/graph in a web browser to test your new API endpoints. If you're using a tool like RStudio Server to run your R code on a remote machine, you should see the [networking section]{#networking} for help on how to visit your API.
